### ISSUE TITLE
Regex error during build

### ISSUE THREAD

**Issue by atrauzzi** [ffMathy/typescript-cs-poco#43]
(I've also opened this ticket on the gulp repo: https://github.com/Evertras/gulp-typescript-cs-poco/issues/7 - feel free to close that one in favour of this.)

Just had this suddenly come back from one of our build servers while generating our models:

```
[17:13:48][Step 4/7]         throw new Error('Regular expression timeout for pattern \'' + regex + '\' and data \'' + input + '\', with ' + sandbox.results.length + ' results gathered so far.\n\nInner error: ' + e);
[17:13:48][Step 4/7]         ^
```

Is it possible that the package was updated recently and that update would have introduced this error?

**Comment by ffMathy** [comment]
I don't have access to that other repo yet.

We could just increase the default timeout.

The thing is that RegEx can (in some scenarios with some input) take very long to run. In regular JavaScript, it is not possible to have a timeout. However, in NodeJS it is. So I made a "safeRegex" function which makes the RegEx execute with a timeout, to instead produce an error in cases where it would elsewise halt the whole build process.

I set the timeout to something quite low, but I believe we could just change it. One moment.

**Comment by ffMathy** [comment]
Fixed in 585737727436c952e221b7c5ba07c7ca97dd50f5. Try with that build.

**Comment by Evertras** [comment]
Added @ffMathy to the other repo as well.

**Comment by ffMathy** [comment]
Might be solved now.
