### ISSUE TITLE
Method regex takes a long time to run with a specific C# attributes usage

### ISSUE THREAD

**Issue by jakubfijalkowski** [ffMathy/typescript-cs-poco#44]
Hello,

Consider this fragment of C#:
```csharp
    [A, B(1)]
    [C(A = "", B = "")]
    public string Prop { get; set; }
```
and the `methodRegex` used in `generateInterface`. This particular combination takes a loong time to run (120s on my machine), even though it is very simple. The fun thing is, matching on this code:
```csharp
[A, B(1)]
[C(A = "", B = "")]
public string Prop { get; set; }
```
is instant (0.07s), and on this:
```csharp
[A, B(1)]
  [C(A = "", B = "")]
    public string Prop { get; set; }
```
is... well... somewhere in the middle (2s). If the first line is split into two separate attributes, like this:
```csharp
    [A]
    [B(1)]
    [C(A = "", B = "")]
    public string Prop { get; set; }
```
everything works as expected (0.05s).

This isn't an edge case, as code with multiple attributes in a single pair of `[]` repeated on multiple lines is quite common.

This is related to #43 and Evertras/gulp-typescript-cs-poco#7 .

**Comment by Rene-Sackers** [comment]
Bit of a late reply, but this may have been solved in https://github.com/ffMathy/typescript-cs-poco/commit/2767e65546bc5b683017c083718e505cebd3bf2d.

**Comment by ffMathy** [comment]
Will close unless it pops up again. Thanks a lot!
