### ISSUE TITLE
Option for ignoring methods

### ISSUE THREAD

**Issue by jonathanp** [ffMathy/typescript-cs-poco#45]
First off I want to thank you for a great module!

Since there seems to be some problems with the `methodRegex` I think the option to ignore methods would be helpful. If you think it's a good idea I'd be happy to submit a PR.

**Comment by Evertras** [comment]
Glad it's helpful!

I think that's fine.  A quick PR would be great.  I'm not quite on top of maintaining this as I used to be. :(
