### ISSUE TITLE
Incorrect definition generated for enum.

### ISSUE THREAD

**Issue by atrauzzi** [ffMathy/typescript-cs-poco#54]
If I assign numbers to my enum values in C#, the outputted TypeScript gets a little confused:

```
    public enum SomeKindOfEnum
    {
        Fill = -1,
        Show = 0,
        ReadOnly = 1,
        AddOnly = 2,
        Edit = 3
    }
```

Renders to:

```
declare enum SomeKindOfEnum{
    Fill = 0,
    -1 = 1,
    Show = 0,
    ReadOnly = 1,
    AddOnly = 2,
    Edit = 3
}
```

**Comment by ffMathy** [comment]
I can't reproduce this. There is even a test that should prevent this. Can you make a test that shows that this is a problem?

**Comment by atrauzzi** [comment]
It's definitely ideal if everyone reporting issues can make tests, but I simply don't have the time to do so.

At the moment we've just had to stop generating TS classes from our C# models.  If I get the time to dig in more, I will.  But as things currently stand, abstract classes and interfaces are just generating empty and enums with negative values are coming out as above.
