### ISSUE TITLE
PrefixWithI and inheritance problem.

### ISSUE THREAD

**Issue by mailivore** [ffMathy/typescript-cs-poco#57]
I have been using this generator for several months but I have an issue that drives me crazy.

Some weeks ago, I updated to the last version (1.12.0 from 1.11.0) and I started seeing an error in my generated definition files. I rolled back to the previous version but the problem came back today.

I have a "Base" class which turned into "IBase" with the "prefixWithI" option on.
All my other classes inherit from this class and that is where the problem happens.
Here are some examples of generated definitions : 
```
export interface IIIIIBase
export interface IIIIIIAgence extends IIIIIIBase 
export interface IIIIIIIAlerte extends IIIIIIIBase 
export interface IIIIIIIIIIIIIIIIIIIIDocumentMainCourante extends IIIIIIIIIIIIIIIIIIIIBase 
```

You can see that I have a random number of prefixed "I" (probably defined by the number of files already generated by the process). 
Everything works well if I disable the "prefixWithI" option.

I don't know is this a problem with my gulp config so I post it here if it can be useful : 
```
gulp.task('clean-poco', function () {
    return gulp.src("typescript-definitions/Models/*.*", { read: false })
      .pipe(clean());
});

var pocoSrc = [
        "../../../DotiEntity/Base.cs",
        "../../../DotiEntity/Credit/*.cs"
];

gulp.task("poco", ['clean-poco'], function () {
    return gulp.src(pocoSrc)
                .pipe(pocoGen({
                    prefixWithI: true,
                    baseNamespace: "Credit",
                    dateTimeToDate: true,
                    customTypeTranslations: {
                        T: "T",
                        byte: "number",
                        DateRange: "DotiUtility.IDateRange",
                        Utilisateur: "DotiUtility.IUtilisateur",
                        Structure: "DotiUtility.IStructure",
                        Societe: "DotiUtility.ISociete"
                    }
                }))
                .pipe(gulp.dest("typescript-definitions/Models"));
});
```

Thanks for your help.

**Comment by ffMathy** [comment]
That indeed sounds like a nasty bug.

Could you make a pull request for fixing it, or perhaps just reproducing it via a test?

**Comment by ffMathy** [comment]
@Rene-Sackers did you decide to look at this at one point, or did you abandon it again?

**Comment by ffMathy** [comment]
Fixed.
