### ISSUE TITLE
Interfaces are empty

### ISSUE THREAD

**Issue by atrauzzi** [ffMathy/typescript-cs-poco#59]
Seems like interfaces are coming out empty.

As are abstract classes.

Was there any kind of regression?

**Comment by atrauzzi** [comment]
@ffMathy - BTW, here's what I'm calling from the gulp-side of things:

```
gulp.task("ts:common-models", function () {

    return gulp.src('Models/Front/**/*.cs')
        .pipe(pocoGen({
            prefixWithI: false,
            propertyNameResolver: function (propertyName) {
                return propertyName[0].toLowerCase() + propertyName.substring(1);
            }
        }))
        .pipe(rename(function (filePath) {

            var parts = filePath.dirname.split(path.sep);

            filePath.dirname = parts[0];
        }))
        .pipe(gulp.dest('Content/src/Model'));
});
```

**Comment by ffMathy** [comment]
If you can make a pull request that has tests that verify the issue, then I will fix it.

**Comment by atrauzzi** [comment]
I'm not even sure what the first thing to do there would be.  I mean, basically I have C# interfaces and abstract classes that are getting generated as empty `.d.ts` files....

**Comment by ffMathy** [comment]
Make a unit test containing your exact C# class to generate or one that replicates the issue, and make it so that the test fails if the output is empty. 

Then make a pull request for that failing test.
